dataset:
  train_images: "./data/train/images"
  train_masks: "./data/train/masks"
  val_images: "./data/val/images"
  val_masks: "./data/val/masks"
  test_images: "./data/testImages"

training:
  batch_size: 8
  learning_rate: 0.0001
  epochs: 20
  num_classes: 10
  image_size: 256

model:
  save_path: "./model.pth"

device: "cuda"
